### ISSUE TITLE
warn when message will be suppressed because notification center is set to Do Not Disturb

### ISSUE THREAD

**Issue by bdefore** [julienXX/terminal-notifier#104]
Running 'terminal-notifier -message foo' provides no output in the case where a user has set Do Not Disturb in their Notification Center preferences. It'd be helpful to know that the message will not be sent due to this configuration.

**Comment by gianpaj** [comment]
+1

**Comment by tmaher** [comment]
https://github.com/julienXX/terminal-notifier/pull/235 adds a `-ignoreDnD` flag to the CLI, using the aforementioned property.

**Comment by julienXX** [comment]
Option is now merged, will be out in the upcoming release.
