### ISSUE TITLE
Option to remove border around the appIcon

### ISSUE THREAD

**Issue by alexgorbatchev** [julienXX/terminal-notifier#108]
I would love to see an option to remove the border around the appIcon, or better yet just not have it at all.

![20140914-075037](https://cloud.githubusercontent.com/assets/65633/4264272/7e25ab52-3c1e-11e4-9958-088819c52443.png)

**Comment by ricardobeat** [comment]
Hi @julienXX, any plans to release a new version? This seems to be the only change to the code besides #113 since the last release.

**Comment by julienXX** [comment]
@ricardobeat sure, expect a new version soon.

**Comment by marszall87** [comment]
What about the small terminal icon? Is there any way to disable it?

**Comment by julienXX** [comment]
@marszall87 yes see #131 answers.
