### ISSUE TITLE
terminal-notifier within node-webkit permission denied

### ISSUE THREAD

**Issue by JacopoDaeli** [julienXX/terminal-notifier#116]
Hi I am trying to use terminal-notifier within node-webkit and it doesn't work.
When I test the app with nodewebkit module it works perfecty, therefore when I pack my app it doesn't work anymore and I get this from my WebKit Console:
`Command failed: /bin/sh: /Users/jacopodaeli/Desktop/PublipingTrainer.app/Contents/Resources/app.nw/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier: Permission denied`

My App is based on Node-WebKit 0.8.6 and it runs over Mac OS X 10.9.

Anyone can help me with this problem?

**Comment by chukkynze** [comment]
Just in case this may help anyone else, the solution to this kind of problem is basically to adjust your file permissions. Most likely, the file `/Users/jacopodaeli/Desktop/PublipingTrainer.app/Contents/Resources/app.nw/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier` is not executable by the user/runner of the script. What you can do is to cd to the directory `/Users/jacopodaeli/Desktop/PublipingTrainer.app/Contents/Resources/app.nw/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/` and check ls -l for the permissions of terminal-notifier. Most likely, you'll be missing an x in the 4th position, in other words, you don't have executable permissions for this file. run `sudo chmod o+x terminal-notifier` to give the owner executable permissions. This should solve this problem
