### ISSUE TITLE
-remove option unreliable/doesn't work

### ISSUE THREAD

**Issue by petere** [julienXX/terminal-notifier#118]
Somehow, the `-remove` option doesn't seem to work anymore.  I'm pretty sure it did at some point.

```
$ terminal-notifier -list ALL
$ terminal-notifier -group foo -message test
# (notification pops up)
$ terminal-notifier -list ALL
GroupID Title   Subtitle    Message Delivered At
foo Terminal    (null)  test    2014-11-08 02:40:18 +0000
```

So far so good.

```
$ terminal-notifier -remove foo
* Removing previously sent notification, which was sent on: 2014-11-08 02:40:18 +0000
$ terminal-notifier -list ALL
GroupID Title   Subtitle    Message Delivered At
foo Terminal    (null)  test    2014-11-08 02:40:18 +0000
```

I can repeat that indefinitely.  It's not a timing issue.

When I close the notification manually in the notification center, then it disappears from the list:

```
$ terminal-notifier -list ALL
$
```

I'm on Yosemite.

Any ideas?

**Comment by petere** [comment]
It happens only with 1.6.2, not with 1.6.1.

**Comment by Martin-Pitt** [comment]
Can also repro this issue by running the same commands.
Just installed 1.6.2 terminal-notifier as a brand new user.

**Comment by applebit924** [comment]
I too have not been able to get this to work when I execute this from a script.  It will work via the command line in the Terminal.

**Comment by petere** [comment]
I could swear that after I upgraded to El Capitan, this worked as intended for about two days, and then it reverted back to the broken behavior described here. So apparently something gets jammed in the system state after a couple of uses.

**Comment by julienXX** [comment]
Closing for now, feel free to re-open if you still have issues.
