### ISSUE TITLE
Make the -remove option (or overwirting with -group) silent

### ISSUE THREAD

**Issue by floweh** [julienXX/terminal-notifier#136]
It would be great if one could overwrite the messages without any feedback in the shell when using `-group`or `-remove`. Currently it gives: `* Removing previously sent notification, which was sent on: 2015-06-29 19:12:30 +0000`. How about a `-silent`switch?

**Comment by julienXX** [comment]
You can do:
```terminal-notifier -remove 123 > /dev/null```
Does that solve your issue?

**Comment by floweh** [comment]
Works perfectly, you might add that to the documentation. Thanks!
