### ISSUE TITLE
Installing Gem version crashes Notification Center

### ISSUE THREAD

**Issue by herrbischoff** [julienXX/terminal-notifier#140]
### Environment

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27
```
```bash
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
```
```bash
$ irssi -v
irssi 0.8.17 (20141011 1044)
```

### Problem

I tried to run `terminal-notifier` along with `irssi` and [this script](https://github.com/paddykontschak/irssi-notifier), which resulted in an instant lockup of Notification Center. CPU usage immediately spikes to 100% and Notification Center becomes unresponsive.

`killall NotificationCenter` does nothing to help, restarting or cache clearing or deleting of preferences does not work as well. I found out that unchecking the following checkbox in the Notifications preference pane, followed by a `killall NotificationCenter` stops the CPU usage and NC becomes responsive again. When checking the box, the previous behavior immediately reappears.

<img width="668" alt="screen shot 2015-08-25 at 01 58 31" src="https://cloud.githubusercontent.com/assets/8957346/9455587/1ff24de2-4acd-11e5-99b7-ef52bb85c3f1.png">

When uninstalling the Gem and installing via Homebrew everything works fine.

**Comment by julienXX** [comment]
That's really weird. Have you noticed other issues not related to your usage with irssi?

**Comment by julienXX** [comment]
Is it possible that you installed the gem version `sudo` like `sudo gem install terminal-notifier`?

**Comment by herrbischoff** [comment]
No, just installed without sudo, as it should be.

**Comment by herrbischoff** [comment]
Since there hasn't been any update regarding this for a long time, I'm closing this.
