### ISSUE TITLE
-execute not working

### ISSUE THREAD

**Issue by ramiroaraujo** [julienXX/terminal-notifier#141]
I've tried both downloading the binary or installing with homebrew. When using the example said to be working from issue #105 it doest work either. It's simply not executing the passed command

Let me know if I can help with anything :)

**Comment by julienXX** [comment]
@ramiroaraujo can you please tell me:
- your OS version
- terminal-notifier version
- how you installed it? (home-brew, gem...)

**Comment by ramiroaraujo** [comment]
OS: 10.10.4
terminal notifier version: 1.6.3
I tried with the pre built binaries and the homebrew version

**Comment by julienXX** [comment]
@ramiroaraujo what happens if you try `terminal-notifier -message test -execute "open /Applications/Safari.app"` ?

**Comment by ramiroaraujo** [comment]
Oookey, suddenly everything it's working just fine. Tmux seems to be the issue here. I've already checked on the tmux issue, and I can verify it works if I use ```reattach-to-user-namespace```

:) cheers!
