### ISSUE TITLE
Start Transmission on click

### ISSUE THREAD

**Issue by mokrinsky** [julienXX/terminal-notifier#142]
I'm launching terminal-notifier with following command:
```bash
terminal-notifier -title 'Image Uploaded' -message 'Message' -sender com.gyazo.mac -sound default
```
In this case, when I click on notification, Transmission starts. Tried to play with `-execute` param, but it doesn't matter for me - it still launches only Transmission.

I'm using the latest version available in Homebrew and OSX El Capitan GM.

**Comment by julienXX** [comment]
I'm not sure what your issue is here. Could you paste the different commands you're trying and their results?
