### ISSUE TITLE
Set stickyness?

### ISSUE THREAD

**Issue by ceilingcat** [julienXX/terminal-notifier#151]
Is it possible to set the stickyness of the notifications on an individual notification basis? I understand that you can choose between Banners (non-sticky) and Alerts (sticky) in the System Preferences (Notifications), but I'd like to change the behavior programmatically for different notifications. Thanks.

**Comment by y** [comment]
I mentioned [this idea](https://github.com/julienXX/terminal-notifier/issues/33#issuecomment-142683092) on a closed ticket:

> Wouldn't it work if you change globally to Alerts from Banners, then accept an expiration option (and default it if not set), then use a LaunchAgent to clean up expired notifcations?

**Comment by ceilingcat** [comment]
What do you mean by "expiration option"?

**Comment by y** [comment]
> What do you mean by "expiration option"?

Each message would have an expiration time so you could specify the level of stickiness. For example, you could make one message stick for 30 seconds, another for an hour, and another indefinite.

**Comment by 1-61803** [comment]
+1 for this option

**Comment by d12frosted** [comment]
I would like to have this feature. Some notifications I am creating via `terminal-notifier` are very important and I don't want to miss them when I am go AFK. It's like calendar notifications. They are shown no mater what - I have to close them manually. And this is great.

**Comment by gateweb** [comment]
+1

**Comment by kolydart** [comment]
I found a way. If I change notification preferences to "alert", the notification remains sticky.
![screen shot 2016-07-03 at 23 00 21](https://cloud.githubusercontent.com/assets/8072845/16547351/3dbcb28e-4173-11e6-850e-9f1967ae64c2.png)

**Comment by rr0ss0rr** [comment]
+1 - Funny, I was just looking how to do this ;-)

**Comment by julienXX** [comment]
You can now do this with 1.7.1 when using `-timeout` option and setting your notification as Alert type.

**Comment by 1-61803** [comment]
`$ terminal-notifier-1.7.1/terminal-notifier.app/Contents/MacOS/terminal-notifier -sender com.apple.backup.launcher -title "Time Machine" -message "test" -timeout 10
@TIMEOUT $ `

On 10.8.5 this command gives the `@TIMEOUT` output after a 10" delay, but the alert type notification remains on screen.

**Comment by y** [comment]
The way timeout is implemented, it keeps the terminal-notifier command running until the timeout has completed. and if you control-c the terminal-notifier process before the timeout, the alert is not closed for you, you have to manually close it. Couldn't the cleanup be handled by a single LaunchAgent so multiple terminal-notifier processes don't have to wait around?
