### ISSUE TITLE
-appIcon presence invokes extra icon

### ISSUE THREAD

**Issue by unknown--** [julienXX/terminal-notifier#153]
If -appIcon is invoked then Terminal's icon is appended for whatever reason. Would it not be cleaner to just have the specified app's icon? I get that you might want to include Terminal's icon because the notification isn't generated naturally but shouldn't the end-user be able to specify this?

Normal:
'/usr/local/bin/terminal-notifier -title 'Download Complete' -message "$TNAME"'

Redundant Terminal icon:
'/usr/local/bin/terminal-notifier -title 'Download Complete' -message "$TNAME" -appIcon /Applications/Transmission.app/Contents/Resources/Transmission.icns'

![Example](http://i.imgur.com/A1AxbBM.png)

**Comment by julienXX** [comment]
Please see #131
