### ISSUE TITLE
Where is I can find  Terminal Notifier-Info.plist

### ISSUE THREAD

**Issue by ev-ta** [julienXX/terminal-notifier#154]
Hi,

I am install application use command:
   ` $ [sudo] gem install terminal-notifier`
and I can find terminal-notifier in the /Applications/
I am try add:
    `<key>NSUserNotificationAlertStyle</key>`
     `<string>alert</string>`

**Comment by julienXX** [comment]
You will find the executable in /usr/local/bin which you should add to your PATH.
