### ISSUE TITLE
-execute command creating a loop in 10.11.2

### ISSUE THREAD

**Issue by craigeley** [julienXX/terminal-notifier#155]
Installed via homebrew. Any time I call an `-execute` command, even a basic one such as `terminal-notifier -message test -execute "open /Applications/Safari.app"`, terminal-notifier creates a new notification that just says "terminal" when I click on it. Here's a screen cap:

http://d.pr/i/WTS4

And idea what's happening here?

**Comment by julienXX** [comment]
Can't reproduce it. Do you still have the issue?

**Comment by craigeley** [comment]
I do still have this issue, yes. Upgraded homebrew and uninstalled and
reintalled terminal-notifier.

> On Mar 16 2016, at 8:28 am, Julien Blanchard
&lt;notifications@github.com&gt; wrote:  

>

> Can't reproduce it. Do you still have the issue?

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on
GitHub](https://github.com/julienXX/terminal-notifier/issues/155#issuecomment-
197328976)![](https://github.com/notifications/beacon/ABW_pC3bMt1H4WfMnn6s7L6l
cqDlBKp6ks5puAV5gaJpZM4HIA15.gif)

**Comment by julienXX** [comment]
@craigeley have you tried with 1.7.1 release?

**Comment by craigeley** [comment]
Just tried now with the new release on 10.12, and everything is working fine. Thanks for going back into this issue!
