### ISSUE TITLE
-appIcon Option Causes Small Terminal Icon Before Title

### ISSUE THREAD

**Issue by Max-108** [julienXX/terminal-notifier#158]
Currently the -appIcon option causes a small Terminal icon before the title.  Is this generated by terminal-notifer, or is this unavoidable NSUserNotification behaviour?

Is it possible for me to prevent the small Terminal icon before the title by any means (such as removing the Terminal.icns resource from the Ruby folder for instance)?

**Comment by julienXX** [comment]
Please see #131
