### ISSUE TITLE
-execute cannot run functions

### ISSUE THREAD

**Issue by 1-61803** [julienXX/terminal-notifier#159]
$ function safari { open -a safari ; }
    $ terminal-notifier -message safari -execute safari

logs

    Mar 26 12:25:56 com.apple.launchd.peruser.501[229] ([0x0-0x113113].nl.superalloy.oss.terminal-notifier[60782]): Exited with code: 1

**Comment by 1-61803** [comment]
This works though
    $ terminal-notifier -message safari -execute "function safari { open -a safari ; } ; safari"

**Comment by yaauie** [comment]
This is likely because the command is invoked in a subshell of _Notification Center_, not a subshell of your current shell, thus it does not (and cannot) inherit user-defined functions from your current shell.

**Comment by 1-61803** [comment]
@yaauie, again, I corrected myself in post 2 — and provided a useful example.
