### ISSUE TITLE
cannot get pipe status

### ISSUE THREAD

**Issue by 1-61803** [julienXX/terminal-notifier#160]
false | true | false ; logger -t 'terminal-notifier pipe status ' $(echo ${PIPESTATUS[*]} | sed 's/ /+/g' | bc)
logs 2, as expected

    /opt/local/bin/terminal-notifier -message 'get that pipe' -execute "false | true | false ; logger -t 'terminal-notifier pipe status ' $(echo ${PIPESTATUS[*]} | sed 's/ /+/g' | bc)"
logs 0, after clicking the notification

**Comment by 1-61803** [comment]
Well, this works

    /opt/local/bin/terminal-notifier -message 'get that pipe' -execute 'false | true | false ; logger -t "terminal-notifier pipe status" $(echo ${PIPESTATUS[*]} | sed "s/ /+/g" | bc)'

`terminal-notifier` could still get better support for executing commands.

**Comment by yaauie** [comment]
Your shell is [expanding the command](http://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html) before it's even getting to `terminal-notifier`; this is not a terminal-notifier bug.

**Comment by julienXX** [comment]
Thanks @yaauie

**Comment by 1-61803** [comment]
@yaauie, I did corrected myself in post #2, I guess. That said, `terminal-notifier` could still get better support for executing commands.
