### ISSUE TITLE
Remove from notification center preferences

### ISSUE THREAD

**Issue by renard** [julienXX/terminal-notifier#163]
I ran `terminal-notifier` with several combinaisons. I seems that for every `sender` ID an new entry is created in the Notification Preferences panel as shown below. Is there a way to remove them?

<img width="652" alt="screen shot 2016-04-04 at 10 35 17" src="https://cloud.githubusercontent.com/assets/383821/14242484/31f624b2-fa51-11e5-9489-ad59512bd961.png">

I unsuccessfully try to remove them by:
- drag them out of the box
- hit the `delete` key (and its metas combinaisons)
- right click

Nothing can do.

Any clue would be appreciated.

Thanks in advance.

**Comment by julienXX** [comment]
@renard you could try the solution described here http://stackoverflow.com/a/12121673

**Comment by renard** [comment]
Unfortunately this directory does not exist on El Capitan.

**Comment by julienXX** [comment]
Hmm I have it on my El Capitan install.

**Comment by renard** [comment]
This may be because you have done some upgrade instead of a fresh El Capitan install.

http://apple.stackexchange.com/questions/156832/where-osx-10-10-notification-center-settings-are-stored

The location had changed you must now use `cd `getconf DARWIN_USER_DIR`/com.apple.notificationcenter/db`


Thanks

**Comment by renard** [comment]
I close this issue since his is not a teminal-notifier related issue.
