### ISSUE TITLE
multi line message

### ISSUE THREAD

**Issue by MoonshineSG** [julienXX/terminal-notifier#164]
Is there a way to send a multiple line message ? 
I tried "abc\nxyz" and  "abc^Mxyz" but it comes out exactly like that instead of the wanted
"abc
xyz"...

**Comment by julienXX** [comment]
Yes two lines maximum:
```
terminal-notifier -message "$(cat <<'EOF'
abc
xyz
EOF
)" -title "Multi line"
```
