### ISSUE TITLE
-sender doesn't work with system preferences

### ISSUE THREAD

**Issue by 1-61803** [julienXX/terminal-notifier#167]
I have a notification that I'd like to open Time Machine preferences when I click on it. It doesn't work, it does nothing. Example
```
terminal-notifier -message test -sender com.apple.prefs.backup
```

**Comment by julienXX** [comment]
You can use execute instead of open:
`terminal-notifier -message test -execute "open -b com.apple.systempreferences /System/Library/PreferencePanes/TimeMachine.prefPane"`

**Comment by 1-61803** [comment]
Thanks for the tip! I just realized `-activate` not `-sender` was the option that didn't work. I emended where necessary.
