### ISSUE TITLE
Executable instead of app

### ISSUE THREAD

**Issue by CarlAndersson** [julienXX/terminal-notifier#168]
alerter by vjeantet is currently distributed as en executable instead of an app, link: https://github.com/vjeantet/alerter
Since that project is originally forked from this one, would it be possible to distribute this project as an executable too? It would simplify the use to be able to install an executable directly in the system path instead of accessing the contents in a bundled app.

**Comment by julienXX** [comment]
It could be. Let me think a bit more on this :)

**Comment by julienXX** [comment]
@CarlAndersson it's planned for the next iteration, I'll keep you posted.

**Comment by julienXX** [comment]
1.8.0 is now packaged as a command-line app.
