### ISSUE TITLE
url should NOT be encoded (or give an option to disable this)

### ISSUE THREAD

**Issue by vmarquet** [julienXX/terminal-notifier#170]
Otherwise there are situations where it's just IMPOSSIBLE to get the url right. Example:
- param1 : `hello`
- param2 : `jules&jim`

Try 1 : `https://site.com/?param1=hello&param2=jules&jim` => terminal-notifier doesn't urlencode the `&` so the param2 is broken => WRONG

Try 2 : `https://site.com/?param1=hello&param2=jules%26jim` => terminal-notifier encodes `%26` into `%2526` => WRONG

**Comment by julienXX** [comment]
Related to #95

**Comment by julienXX** [comment]
Fixed in 1.8.0.
