### ISSUE TITLE
Click action with the same "-sender" closes the last notification

### ISSUE THREAD

**Issue by R0maric** [julienXX/terminal-notifier#175]
Hello,
By executing simultaneously several terminal-notifier -actions and clicking an action, it closes the last notification with the same "-sender".

If I open 3 tabs of the Terminal and I execute : tab n°1 = 
`terminal-notifier.app/Contents/MacOS/terminal-notifier -actions Action1 -message Message1`
then tab n°2 = 
`terminal-notifier.app/Contents/MacOS/terminal-notifier -actions Action2 -message Message2`
then tab n°3 = 
`terminal-notifier.app/Contents/MacOS/terminal-notifier -actions Action3 -message Message3`
Then I click on Action1. 

In Terminal:
tab n°1 = Action1
tab n°2 = still running
tab n°3 = @CLOSED

By cons, if each notif has a "-sender" different everything works.

**Comment by julienXX** [comment]
Hi @R0maric since Actions are no longer supported I'll close this issue. You can open a new one on the alerter repo if you still have this issue.
