### ISSUE TITLE
Keep notification on screen while timeout is active

### ISSUE THREAD

**Issue by martinvandiemen** [julienXX/terminal-notifier#179]
The notification message disappears after 5 seconds. Could this be matched with timeout? So if a timeout of 30 seconds is set the notifications stays on the screen for 30 seconds?

Thanks again!

**Comment by kootenpv** [comment]
Very surprised that indeed "timeout" did not do what I expected it to do.

**Comment by julienXX** [comment]
You have to set your notification to Alert type for it to work.

**Comment by martinvandiemen** [comment]
Hi @julienXX, could you please give me an example? Thanks!

**Comment by julienXX** [comment]
@martinvandiemen in your preferences, you must set you notifications for terminal-notifier like this https://www.dropbox.com/s/n2kt0in8q6syiu6/Screenshot%202016-10-11%2014.27.27.png?dl=0

**Comment by martinvandiemen** [comment]
@julienXX, sorry I was looking at one of the options. This makes sense although it's hard to manage those setting via terminal. Each sender has it's own item in Notifications. Would it be possible to manage the alert option via terminal-notifier? Thanks again!

**Comment by julienXX** [comment]
@martinvandiemen I haven't found how to manage those settings so far.

**Comment by rr0ss0rr** [comment]
I have Alerter set up as "Alerts" in notification center and Terminal-notifier as "Banners".  I was hopeful  that with the new code, I would be able to have a "Banner" act as an "Alert".  Alerter is used only in the situations where I want the message to stay on the screen until I click on it.  For the most part, I just want Terminal-notifier to act as "Banners" so I don't want to set Terminal-Notifier messages to be Alerts in Notification center.

**Comment by julienXX** [comment]
@rr0ss0rr unfortunately it's not possible, OSX Banner notification have a default timeout of 5 seconds. It works if you set the -timeout to less than 5 seconds but that's not very useful. So in Banner mode -timeout option is kinda useless.

**Comment by rr0ss0rr** [comment]
Can terminal-notifier some how be registered twice in Notification Center?  Then you can set one as alerts and the other as banners. Probably not.

**Comment by julienXX** [comment]
Probably not but I'll check.

**Comment by kootenpv** [comment]
@rr0ss0rr Ironically I have like 5 versions showing up there. Somehow they are not removed from there when we uninstall previous versions. So, I'm actually pretty convinced it should be possible: just install 2 different versions and make sure they do not collide (then again, I'm not at all associated with this project, so what do I know).

**Comment by julienXX** [comment]
@rr0ss0rr @kootenpv yes you have a terminal-notifier per terminal-notifier version so maybe there is something to be done here.

**Comment by rr0ss0rr** [comment]
Perhaps there is a way to create a separate bootstrap that calls terminal-notifier where it could have it's own notification center entry .. ie terminal-notifier-alert
