### ISSUE TITLE
`-open` does not work in 10.11

### ISSUE THREAD

**Issue by henrydobson** [julienXX/terminal-notifier#181]
Looks like the issues are counting up here. Is this project still maintained?

**Comment by julienXX** [comment]
Yes it is still maintained. Which version do you use? Which notification style do you use (Banner or Alert)?

**Comment by henrydobson** [comment]
That's good news! I really like having this feature. 

I'm using version 1.7.1.
Here are some examples. I have found the following behaviours unintuitive but I understand there's a bug here.

.1. a) `terminal-notifier -title "Title" -message "Message"  -open https://google.com -sender com.example.app`
.1. b) `-open` does not work

.2. a) `terminal-notifier -title "Title" -message "Message"  -execute 'open https://google.com' -sender com.example.app -alerts OK`
.2. b) Clicking OK does not open URL. Clicking the notification runs executable.

.3. a) `terminal-notifier -title "Title" -message "Message"  -open https://google.com -sender com.example.app -timeout 10`
.3. b) Workaround. This allows `-open` to work.

**Comment by julienXX** [comment]
Thanks for the detailed examples. This is a bug, I'll look into it.

**Comment by reitermarkus** [comment]
Hi, also just ran into this on 10.11. Trying to open a `.log` file in Console.app using a `file://` URL.

I found out that using `-open` in combination with `-action ''` makes clicking on the notification open it as it should when only `-open` is specified.

I also tried using `-execute "open 'file://…'"`, which also did nothing.

**Comment by Glutexo** [comment]
Just adding a „me too“ here. The workaround with `-action ''` doesn’t work for me though.

**Comment by dpfbop** [comment]
Same issue here :(

**Comment by okkedek** [comment]
Try `-actions ''`, that worked for me

**Comment by johandalabacka** [comment]
I can confirm it is the same problem on MacOS 10.12 and the workaround using -actions '' or -timeout 10 works there also. This is on the prebuild 1.7.1.

**Comment by teamcoltra** [comment]
:) Just a +1 that this is still happening. Or at least it is for me. I tried 'actions' and this did not fix it. 10.12.4

**Comment by julienXX** [comment]
Fixed in 1.8.0.

**Comment by dkristian** [comment]
I upgraded to 1.8.0 today and started receiving a message that the argument being passed to `-open` is not a valid URI.

In case it helps anyone else, I needed to change the argument format from `file:/absolute/path/to/file` to `file://$HOSTNAME/absolute/path/to/file`.

For some reason, `file:///absolute/path/to/file` is also reported as being invalid.

**Comment by julienXX** [comment]
@dkristian yes it's fixed on the master branch but I'll wait a bit before releasing a new version.

**Comment by mafrosis** [comment]
> terminal-notifier -message egg -open "$(pwd)"
    2017-06-26 11:39:19.656 terminal-notifier[52478:9324995] ApplePersistence=NO
    2017-06-26 11:39:19.670 terminal-notifier[52478:9324995] '/Users/mafro' is not a valid URI
