### ISSUE TITLE
Aliases don't work with -execute 

### ISSUE THREAD

**Issue by trevorpburke** [julienXX/terminal-notifier#183]
I have some aliases I'd like to use within the -execute argument, but they don't seem to be working. Any idea why?

**Comment by julienXX** [comment]
@trevorpburke still having the issue?

**Comment by trevorpburke** [comment]
I attempted your suggestion, but was having issues accessing that file on
my work machine. No longer work there, will check on my home machine later
today.

**Comment by tewe** [comment]
So you mean shell aliases, not symlink aliases.

**Comment by trevorpburke** [comment]
yes, shell aliases
