### ISSUE TITLE
terminal-notifier crashes when -dropdownLabel options is given but -closeLabel not

### ISSUE THREAD

**Issue by vam** [julienXX/terminal-notifier#186]
I'm on OS X 10.12.

__To reproduce:__
 1. Run `terminal-notifier -message "Test" -actions A,B,C -dropdownLabel 'Options'`
 2. Click on 'Options' when the noficiation appears.

__What happens:__
  terminal-notifier crashes due to uncaught exception:
    'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 9223372036854775807 beyond bounds [0 .. 2]'

_Thank you for your work on terminal-notifier!_

**Comment by julienXX** [comment]
Not reproducible on my 10.12 box, sorry. Can you confirm you have the latest version? How did you install it (gem, brew...)?

**Comment by vam** [comment]
@julienXX Hi! I've installed terminal-notifier over gem. The version is 1.7.1. I've tried that with brew (which also installed the 1.7.1 version) but with the same result.

**Comment by stetner** [comment]
Same issue here on 10.12.1 - with brew version as well as downloaded binary.

**Comment by gniemetz** [comment]
I have the same issue on OS X 10.11.6, terminal-notifier 1.7.1 installed via brew

**Comment by julienXX** [comment]
@vam @stetner @gniemetz can you confirm you had your notifications set as Alerts and not Banners? (cf. https://github.com/julienXX/terminal-notifier#caveats)

**Comment by stetner** [comment]
Alerts setting fixes it for me.
