### ISSUE TITLE
closeLabel not displaying a close button

### ISSUE THREAD

**Issue by drukepple** [julienXX/terminal-notifier#190]
Using the examples in the readme that use `-closeLabel`, a notification appears but does not have any buttons on it.

This example:

`$ terminal-notifier -title ProjectX -subtitle "new tag detected" -message "Deploy now on UAT ?" -closeLabel No -actions Yes -appIcon http://vjeantet.fr/images/logo.png`

Give me this result:

![image](https://cloud.githubusercontent.com/assets/323519/21434947/38af1546-c834-11e6-9e43-741d5ecd3419.png)

I'm on 10.12.1 and installed via brew.

**Comment by julienXX** [comment]
@drukepple even when you hover the notification?

**Comment by julienXX** [comment]
@drukepple still having this issue?

**Comment by M0rph3v5** [comment]
had the same issue, was looking all over, turns out it was default on banners instead of alerts.

**Comment by julienXX** [comment]
Thanks @M0rph3v5, I'm closing the issue for now, @drukepple feel free to re-open it if you still have the issue.

**Comment by drukepple** [comment]
Maybe I'm confusing what the expected behavior is.  The notification disappears after a few seconds; I thought that if you were requesting input from the user (via buttons) then the notification would hang around until dismissed. As it was, the notification never stayed up long enough for me to click on anything (turns out: the buttons were there, but only visible after hovering over the notification). Meanwhile, the command line never received any kind of reply and was "hanging." I'm not sure what the intention is, but it seems to me that if you are expecting/requiring user input, then the notification shouldn't disappear until the user interacts with it.

Again, I'm just using the example provided in the readme:
`terminal-notifier -title ProjectX -subtitle "new tag detected" -message "Deploy now on UAT ?" -closeLabel No -actions Yes`.  I see no buttons unless I manage to hover over the notification before it slides away. The terminal goes into a state of waiting for something happen before exiting terminal-notifier, but if the notification slides away, there's no other option other than Control-C.  Am I using this wrong?

**Comment by julienXX** [comment]
@drukepple you must first set your alert type to Banner like this https://www.dropbox.com/s/6v29vakaiqigfme/Screenshot%202017-04-11%2012.26.52.png?dl=0

**Comment by drukepple** [comment]
Oh, my gosh. That's what was going on? It works now, thank you. I don't see any mention of this in the Read Me...maybe add an item under "Caveats"?

**Comment by julienXX** [comment]
@drukepple Good idea! Do you want to open a pull-request with some Readme update?

**Comment by drukepple** [comment]
Done...open to feedback if you don't like the wording or whatever.
