### ISSUE TITLE
App Transport Security is blocking a cleartext HTTP

### ISSUE THREAD

**Issue by arguiot** [julienXX/terminal-notifier#191]
There is a problem with the `info.plist` file. When I'm trying to load an icon from a server that doesn't support HTTPS, this is what I'm getting:
`2016-12-28 15:48:22.483 terminal-notifier[71267:1773514] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.`

I hope you'll fix it, but if you really don't have time, I will, and I'll do a pull request! 😄 

See this for the solution (It worked for me on an ios app) : 
[StackOverflow - App Transport Security](http://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http)

**Comment by julienXX** [comment]
The code to fix this has already been merged (https://github.com/julienXX/terminal-notifier/pull/177) I just need to make a new release :)

**Comment by julienXX** [comment]
Available in 1.7.2.
