### ISSUE TITLE
package as script

### ISSUE THREAD

**Issue by moshed** [julienXX/terminal-notifier#193]
i realize you intentionally packaged this as an app to prevent a bug but a fork of your project (https://github.com/vjeantet/alerter) works without needing to be bundled as a script any chance you can merge that?

**Comment by julienXX** [comment]
@moshed it's planned for the next iteration. I'll keep you posted.

**Comment by julienXX** [comment]
Same as #168

**Comment by julienXX** [comment]
@moshed Fixed in 1.8.0.
