### ISSUE TITLE
Allow overriding notification style setting

### ISSUE THREAD

**Issue by moshed** [julienXX/terminal-notifier#194]
currently if the app your spoofing using `-sender ID` has its notifications set to alert there is no way to get it to show a plain banner. any way to chnage this?
<img width="1680" alt="2017 01 05-12 07 32" src="https://cloud.githubusercontent.com/assets/8683379/21689810/a5f634a2-d33f-11e6-9cb7-8ab71f850d12.png">

**Comment by julienXX** [comment]
There is no API allowing terminal-notifier to do that. See https://github.com/julienXX/terminal-notifier/issues/33
