### ISSUE TITLE
On macOS Sierra actions are always shown

### ISSUE THREAD

**Issue by Paschalis** [julienXX/terminal-notifier#195]
Running this example, shows the "Close" and "Show" buttons from documentation:
`echo 'Piped Message Data!' | terminal-notifier -sound default`

![screen shot 2017-01-17 at 00 26 38](https://cloud.githubusercontent.com/assets/1271164/22001115/b35036c4-dc4b-11e6-946f-d39429ef1257.png)

According to documentation it should have been like this:
![Documentation example](https://github.com/julienXX/terminal-notifier/blob/master/assets/Example_1.png?raw=true)

**Comment by julienXX** [comment]
Could it be that you set your notification type to "Alert" instead of "Banner" in your notification preferences? https://www.dropbox.com/s/og1hl6padpujlu8/Screenshot%202017-01-17%2017.01.53.png?dl=0

**Comment by Paschalis** [comment]
My bad @julienXX , you are correct. BTW thanks for such a nice plugin.

**Comment by m-sureshraj** [comment]
Hi @julienXX if terminal-notifier alert style is 'Alert' then is it possible to hide the actions?
Show only close button.

**Comment by julienXX** [comment]
@m-sureshraj I don't think it's possible.
