### ISSUE TITLE
Add to homebrew-cask

### ISSUE THREAD

**Issue by ecbrodie** [julienXX/terminal-notifier#197]
I have terminal-notifier installed via Homebrew installation.

terminal-notifier has a `.app` file component and that has been historically installed to my system's main list of applications (the `/Applications` directory) via the `brew linkapps` command.

However, there is a change to how Homebrew is having their forumulas install GUI apps. The preferred method is to install the app via `brew cask install` instead of using `linkapps`. See here: https://github.com/caskroom/homebrew-cask/issues/13201

As such, can we have terminal-notifier please support a `brew cask install` command?

**Comment by julienXX** [comment]
Hi @ecbrodie sure I'll try to do it.

**Comment by vitorgalvao** [comment]
@ecbrodie [Make a request](https://github.com/caskroom/homebrew-cask/issues/new?title=Cask%20request%3A%20%5Bapp%20name%20here%5D&body=%23%23%23%20Cask%20details%0A%0APlease%20fill%20out%20as%20much%20as%20possible.%20Before%20you%20do%2C%20note%20%2A%2Awe%20cannot%20support%20Mac%20App%20Store-only%20apps%2A%2A.%0A%0AName%3A%0A%0AHomepage%3A%0A%0ADownload%20URL%3A%0A%0ADescription%3A%0A) for it and someone will probably submit it within a day (I’m a maintainer, and see it happen constantly).

However, for us to accept it in HBC it’ll also have to be removed from [HB](https://github.com/homebrew/homebrew-core) (we try to not have duplicates between the projects.

**Comment by julienXX** [comment]
@ecbrodie the upcoming version won't be packaged as an app any longer and just as a command line tool so I'm not sure it will be needed.

**Comment by julienXX** [comment]
1.8.0 is no longer a .app so I'll close this issue.

**Comment by vitorgalvao** [comment]
@julienXX But this means we now lost the ability to set a custom icon on the app bundle. Since `-sender` is insufficient (it still leaves a small terminal icon in the title of the notification) what do you suggest now?

**Comment by julienXX** [comment]
@vitorgalvao Since it's a command line app, the small terminal icon is no longer here.

**Comment by vitorgalvao** [comment]
@julienXX My mistake, I didn’t mean `-sender` (that one didn’t show the little terminal icon), I meant `-appIcon`.

**Comment by julienXX** [comment]
@vitorgalvao changing the icon on the binary with command+i as you would for any file seems to work well.

**Comment by vitorgalvao** [comment]
@julienXX Oh, that’s even more convenient! That method is really useful. It should be part of the README.

**Comment by vitorgalvao** [comment]
Actually, I take it back. It is indeed convenient, but since macOS will then cache the icon, it isn’t reliable if you want to do it multiple times.

**Comment by julienXX** [comment]
@vitorgalvao yes it seems to work only once and then OSX caches the icon forever it seems.

**Comment by julienXX** [comment]
@vitorgalvao found a way to refresh the icon:
`$ rm $(getconf DARWIN_USER_DIR)com.apple.notificationcenter/db/*`
then restart Notification Center via the Activity Monitor. If it works for you too, I'll add it to the README.

**Comment by vitorgalvao** [comment]
@julienXX That will not solve embedding `terminal-notifier` in other applications, which is what I used to do, and the main point of changing its icon.

That solution will take care of the icon *once*, but as soon as you have two different `terminal-notifier` binaries on the system, both with different icons, it will no longer work. This makes changing the icon of the binary an insufficient solution for sharing apps with an embedded `terminal-notifier`. `-sender` is the only acceptable solution.
