### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by tanrax** [julienXX/terminal-notifier#199]
echo 'Piped Message Data!' | terminal-notifier -sound default
2017-02-16 10:14:02.845 terminal-notifier[76166:184478] NSNotificationCenter connection invalid

**Comment by julienXX** [comment]
Hello @tanrax 
Can you give me some more information like:
- OSX version
- terminal-notifier version
- how you installed it (homebrew, gem, other)
- did it work before?
- have you tried to re-install it?

**Comment by tanrax** [comment]
of course!

OSX version: 10.12.3
terminal-notifier version> last
how you installed it (homebrew, gem, other): homebrew
did it work before?: yes
have you tried to re-install it?: yes

**Comment by julienXX** [comment]
Thanks, does it fail with other options too or just with `|` and/or `-sound`?

**Comment by tanrax** [comment]
echo 'Piped Message Data!' | terminal-notifier
2017-02-16 10:27:10.115 terminal-notifier[83163:200218] NSNotificationCenter connection invalid

**Comment by julienXX** [comment]
Are you using tmux or another kind of sub-shell?

**Comment by julienXX** [comment]
Could you try if `osascript -e 'display notification "test" with title "TEST"'` has also an invalid connection to NSNotificationCenter?

**Comment by tanrax** [comment]
You are right. It is for the Tmux. I feel the confusion XD

**Comment by julienXX** [comment]
@tanrax no worries, here are some tips regarding terminal-notifier & tmux https://github.com/julienXX/terminal-notifier/issues/115

**Comment by luchofariello** [comment]
@julienXX hi julien, 


I run a process from launchctl (LaunchDaemon) and it gives me error:
2017-05-22 15: 16: 48.109 terminal-notifier [35828: 581946] NSNotificationCenter connection invalid
2017-05-22 15: 16: 48.109 terminal-notifier [35828: 581946] Connection to notification center invalid. ServerConnectionFailure: 1 invalidated: 0

I am executing it like this:
/Users/user/terminal-notifier -title "title" -subtitle "subtitle" -message "message" -actions "actions1","actions2" -dropdownLabel "dropdownLabel" -appIcon pathalert.icns -sound "frog" -timeout 120


If I run it directly manual it works correctly.

Thank you very much, I hope to answer.
