### ISSUE TITLE
Using terminal-notifier from the `at` command

### ISSUE THREAD

**Issue by metadave** [julienXX/terminal-notifier#200]
Hello, I'm trying to use terminal-notifier from an `at` command, but it's failing with a `NSNotificationCenter connection invalid` error.

I'm using OSX 10.12.3.

To reproduce the error:

```
If you haven't enabled `atrun` yet:
# sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.atrun.plist

at + 1 minute <<EOF
/usr/local/bin/terminal-notifier -title ProjectX \
    -subtitle "new tag detected" \
    -message "Deploy now on UAT ?" \
    -closeLabel No \
    -actions Yes > /Users/someuser/foo.out 2>&1
EOF
```

A minute later, check the contents of `/Users/someuser/foo.out`

```
2017-02-16 11:40:16.470 terminal-notifier[12509:135379] NSNotificationCenter connection invalid
2017-02-16 11:40:16.470 terminal-notifier[12509:135379] Connection to notification center invalid. ServerConnectionFailure: 1 invalidated: 0
```

Running `terminal-notifier` outside of `at` works perfectly. Any ideas?

**Comment by julienXX** [comment]
NSNotificationCenter seems to be unavailable outside of logged user space which looks like to be the case when using `at` or `tmux`.

**Comment by metadave** [comment]
got it, thanks for the reply! feel free to close, I'm using `wall` instead for now.

**Comment by goromlagche** [comment]
I came across this issue while searching for solution. Just wanted to update, using `reattach-to-user-namespace` works. 

In my case I am using 
```
echo "reattach-to-user-namespace osascript -e 'display notification \"Make tea\" with title \"☕️\" sound name \"Glass\"'" | at now + 1 minute
```
