### ISSUE TITLE
Running the app with NEXT_ROOT env variable.

### ISSUE THREAD

**Issue by redron** [julienXX/terminal-notifier#201]
Not sure how it might be on different environments, but on my Mac OS (10.12.2 (16C67)) I have discovered experimentally that once you define the following environment variable:

`export NEXT_ROOT=/some/root/
`
terminal-notifier starts failing miserably after each run and gets back to normal once variable is removed:

```
$ export NEXT_ROOT=/tmp/

$ terminal-notifier
2017-02-22 22:20:13.896 terminal-notifier[4839:130595] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Critical error: required built-in appearance SystemAppearance not found'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffc52fee7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffd9ee9cad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffc537d99d +[NSException raise:format:] + 205
	3   libdispatch.dylib                   0x00007fffda7970b8 _dispatch_client_callout + 8
	4   libdispatch.dylib                   0x00007fffda797075 dispatch_once_f + 38
	5   AppKit                              0x00007fffc2d64828 -[NSApplication init] + 1102
	6   AppKit                              0x00007fffc2d641fa +[NSApplication sharedApplication] + 142
	7   AppKit                              0x00007fffc2d65a0b NSApplicationMain + 352
	8   libdyld.dylib                       0x00007fffda7cd255 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

$ unset NEXT_ROOT

$ terminal-notifier
terminal-notifier (1.7.1) is a command-line tool to send OS X User Notifications.

Usage: terminal-notifier -[message|list|remove] [VALUE|ID|ID] [options]

   Either of these is required (unless message data is piped to the tool):

       -help              Display this help banner.
                                   ...
```

Please advice what might be reason and solution. For now issue makes the utility incompatible with our main scenario.

Thanks

**Comment by julienXX** [comment]
Hi @redron thanks for the report. I really have no idea why it occurs as this variable is never used in terminal-notifier. I believe this is macOS related but I really have no clue sorry. I'll close the issue, don't hesitate to re-open it if you have some more informations.

**Comment by alexanderuv** [comment]
@redron just FYI, this variable is related to macOS internals - you know - NeXT OS
I have the same issue with a different use case, but basically a lot of apps fail if that env var is defined. I hope Apple removes it at some point since it seems to be a leftover from a previous architecture

**Comment by redron** [comment]
I appreciate your note @alexanderuv. I hope Apple gets read of that "heritage" someday soon.
