### ISSUE TITLE
-timeout not functioning as expected

### ISSUE THREAD

**Issue by shannon-pasto** [julienXX/terminal-notifier#202]
It appears as though the "-timeout' option isn't working as expected. If I add "-timeout 20", the notification closes after about 5 seconds, however the Terminal command continues to run for 20 seconds.

Thanks,
Shannon

**Comment by charle692** [comment]
@shannon-pasto I believe that the -timeout option only works when you set your notification type as alert.

**Comment by danshaw** [comment]
I'm also having the same issue. Making the notification type to alert provides a box that doesn't go away at all and has the "Close" and "Show" buttons. Making the type to banner should be correct type, but using the "-timeout" option doesn't work like @shannon-pasto mentions. I'm using MacOS 10.12.3.

**Comment by julienXX** [comment]
As @charle692 wrote you need to have the alert type if you want long persisted notifications (>8s I believe). OS X has a default persistence time for notifications, see http://osxdaily.com/2014/01/29/change-notifications-banner-time-mac-os-x/ that affects banner mode. Not sure if the commands in the link still work though.
