### ISSUE TITLE
MacOsx Sierra Terminal-notifier not opening

### ISSUE THREAD

**Issue by jovendor** [julienXX/terminal-notifier#208]
After software update to Sierra it stopped working. I erased and reinstalled it completely but still not working. Is there anything I can do to fix this problem?
Thanks in advance

**Comment by julienXX** [comment]
Hi @jovendor, how did you install it (homebrew, gem, other)? Is it the latest version? Are you using tmux?

**Comment by jovendor** [comment]
I did Homebrew and reinstalled again. It seems that I had no been applying the correct command. Thanks for your prompt answer.  Now I got it working
