### ISSUE TITLE
notification times out even though user has hit reply

### ISSUE THREAD

**Issue by n1ck3** [julienXX/terminal-notifier#209]
# Background

I am using terminal-notifier where I want to give the user an option to change a default value.
I want to give the user 2 seconds to hit "Reply" or else my program will use the default value.

# Steps to reproduce

Issue the command:

```
terminal-notifier -message "Duration is set to 5s. Change by hitting 'Reply'." -timeout 2 -reply
```

# Issue

The notification times out and returns "@TIMEOUT" even though user has hit reply.

# Expected behaviour

The timeout should stop and wait indefinitely for user to either "Reply" or "Close" the notification when the user has hit "Reply."

# Side note (feature request)

It would be nice to change the title of the "Reply" button. 😁

**Comment by julienXX** [comment]
Hi @n1ck3 thanks for the report. I'll look into it and let you know it's possible.

**Comment by julienXX** [comment]
Version 2.0.0 as been released with alerter features removed https://github.com/julienXX/terminal-notifier/releases/tag/2.0.0 so this issue is not relevant anymore as the reply flag is no longer available.
Closing for now, feel free to re-open.
