### ISSUE TITLE
Shell wrapper 

### ISSUE THREAD

**Issue by marcastel** [julienXX/terminal-notifier#211]
Here is a small Korn shell wrapper (which should be more ressource friendly than loading Ruby or other *fat* scripting environments).

https://gist.github.com/marcastel/16d029b70383de0eae37b0407d893d58

This wrapper relies on Korn shell features and syntax, so don't expect it to work with regular Bourne or Bourne again shells, or other shells such as csh or zsh.

**Comment by julienXX** [comment]
Thanks!
