### ISSUE TITLE
1.8 breaks open with local files (without hosts)

### ISSUE THREAD

**Issue by mikaelbr** [julienXX/terminal-notifier#215]
# Please check everything that applies to your issue:
- [x] I looked in closed issues and it has not already been answered
- [x] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- macOS 10.12.5
- terminal-notifier 1.8
- Through binary download

# Reproduce

Run command with `file://` as open.

This commit (https://github.com/julienXX/terminal-notifier/commit/94738f8ac9acec635704d5716267856707306857), is a stricter check on URL and causes local files to no longer work as it requires host. Is this intentional?

**Comment by julienXX** [comment]
It's not intentional sorry, I'll try to fix it quickly.

**Comment by mikaelbr** [comment]
Thanks for the incredibly swift reply. 👍

**Comment by julienXX** [comment]
It does work if you comply with the file:// protocol though:
`terminal-notifier -message 'hello' -open file://localhost/Users/julien/Downloads/IMG_0317.JPG` worked for me.

**Comment by mikaelbr** [comment]
Hm. That's fascinating. For some reason I've never seen using localhost as host on the file scheme before. That does seem to work. But `file:///Users/julien/Downloads/IMG_0317.JPG` without host doesn't. Is `file:///Users/julien/Downloads/IMG_0317.JPG` actually invalid?

**Comment by julienXX** [comment]
Both syntax are valid https://en.wikipedia.org/wiki/File_URI_scheme, I'll update the code accordingly :)

**Comment by julienXX** [comment]
Fixed, I'll wait a bit for more issues before releasing a new version.

**Comment by mikaelbr** [comment]
Great. Thank you
