### ISSUE TITLE
notification does not appear on the screen with -sender com.apple.Terminal

### ISSUE THREAD

**Issue by nhooyr** [julienXX/terminal-notifier#216]
# Please check everything that applies to your issue:
- [x] I looked in closed issues and it has not already been answered
- [ ] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- the macOS version you use macOS 10.12.5
- terminal-notifier version 1.8
- how did you install terminal-notifier (binary download, homebrew, ruby gem...)? homebrew
- step-by-step reproduction instructions

```
$ terminal-notifier -sender com.apple.Terminal -message foobar
```

The notification will not popup on the side of the screen, but if you swipe to the Notification Center, you will see it.

If you add the `-activate` flag, you will see the notification:
```
$ terminal-notifier -sender com.apple.Terminal -activate com.apple.Terminal -message foobar
```

**Comment by julienXX** [comment]
Thanks for the repport, I'll investigate.

**Comment by julienXX** [comment]
What's weird is that if you use Safari or Finder for sender the notification shows up.

**Comment by luckman212** [comment]
I have the exact same issue, except with "Preview.app" (bundle ID=`com.apple.Preview`)

This is w/ version 2.0.0

**Comment by franciscolourenco** [comment]
I have the same, but only when attached to tmux with `-sender com.googlecode.iterm2`.

**Comment by joeynotjoe** [comment]
I am having a very similar issue. I'm attempting to call terminal-notifier as a subprocess in a lua script, it shows up in the sidebar, but doesn't pop up on the screen.	If I run the same code in terminal, it _does_ pop up on the screen (and show up in the sidebar, of course). I'm on terminal-notifier 2.0.0, macOS 10.13.4.

```
terminal-notifier -title iina -subtitle subtitle_contents -message message_contents -sender com.colliderli.iina
```

**Comment by nhooyr** [comment]
I can't reproduce this anymore. I get the notification now. On latest macOS stable.

**Comment by nhooyr** [comment]
Ah it only shows up if you aren't focused on the terminal. E.g. if you run `sleep 2; terminal-notifier ...` and focus safari for example in between, the notification will arrive.

**Comment by nthapaliya** [comment]
This is still an issue. When the -sender is the same as the active window, the notification goes to the sidebar but doesn't pop up on screen.

**Comment by julienXX** [comment]
I'm afraid I can't fix that, I don't see anything in the Apple API that would allow me to do that.

**Comment by Feuermurmel** [comment]
> @nthapaliya I'm afraid I can't fix that, I don't see anything in the Apple API that would allow me to change that.

This totally makes sense. I see two options (non-exclusive):

- Add this to section _Caveats_ in the readme.
- Print a warning to the console if this case can easily be detected. (would have saved me some time because I tested in Terminal.app with different bundle IDs and noticed that _only_ com.apple.Terminal wasn't working…)

Otherwise totally great software, thanks! <3
