### ISSUE TITLE
Where's the .app in 1.8.0?

### ISSUE THREAD

**Issue by majorsl** [julienXX/terminal-notifier#217]
# Please check everything that applies to your issue:
- [X] I looked in closed issues and it has not already been answered
- [X] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- the macOS version you use
10.12.5
- terminal-notifier version
1.8.0
- how did you install terminal-notifier (binary download, homebrew, ruby gem...)?
Homebrew
- step-by-step reproduction instructions

Homebrew upgraded terminal-notifier to 1.8.0, there no longer seems to be a .app.  I tried

brew uninstall terminal-notifier
brew install terminal-notifier

to no avail, I still only see:

/usr/local/opt/terminal-notifier/bin is terminal-notifier

No .app one level up either.

The README still seems to indicate that a .app is necessary to make use of it when installed from Homebrew, and scripts I use that call it no longer work.

**Comment by julienXX** [comment]
Yes the .app bundle is now a classic command line executable. Sorry I'll update the README accordingly.

**Comment by majorsl** [comment]
Ah, thanks. I assume there were other changes as well since even the basic:

echo 'Piped Message Data!' | terminal-notifier -sound default

no longer displays a notification for me even when using the full path eg:

echo 'Piped Message Data!' | /usr/local/bin/terminal-notifier -sound default

I'll wait for the documentation.

**Comment by julienXX** [comment]
Hmm every example in the README should still work though. Can you try them and let me know which ones have issues on your side?

**Comment by majorsl** [comment]
In playing around, it seems that it won't display unless I include -sender.

terminal-notifier -sender com.apple.Terminal -message "Hello"

And, like in #216, it only shows on-screen badges if I include -activate.

However, as an additional note for the above, even using -activate in conjunction with something like -contentImage will only display in the sidebar notification center - no badge.

**Comment by JayBrown** [comment]
Yeah, v1.8.0 is still buggy. Doesn't display without sender. (OS X 10.11.6)

**Comment by julienXX** [comment]
@majorsl @JayBrown I'll look into it.

**Comment by JayBrown** [comment]
It's not that big of a deal, I assume, because you can simply add `-sender Finder`, and you're good. By the way, in my [**notify function**](https://github.com/JayBrown/notify/blob/master/notify.sh) I'm checking whether tn is installed, and if so, whether it's the old version (<1.8) or newer. In this regard, it would be great to have the argument `terminal-notifier --version` to print the current version number to stdout. Currently I need to grab it from the help output.

**Comment by julienXX** [comment]
@JayBrown `-version` will be in the upcoming release.
