### ISSUE TITLE
Cannot open url although ACTIONCLICKED is seen in terminal when I tap on 'Show'

### ISSUE THREAD

**Issue by khantthulinn** [julienXX/terminal-notifier#221]
- the macOS version you use - 10.12.4
- terminal-notifier version - terminal-notifier-1.8.0
- how did you install terminal-notifier (binary download, homebrew, ruby gem...) - I use gem
- Ruby version - 2.2.6

I am trying to run this command and when I tap on 'Show', it doesn't open webpage.

`$ terminal-notifier -title '💰' -message 'Check your Apple stock!' -open 'http://finance.yahoo.com/q?s=AAPL'
`

I saw in my terminal like this. It look like it trigger action but it doesn't open webpage. How shall I do?

> Khants-MacBook-Pro-2:OneChangi khantthulinn$ terminal-notifier -title '💰' -message 'Check your Apple stock!' -open 'http://finance.yahoo.com/q?s=AAPL'
> 2017-05-24 09:55:56.986 terminal-notifier[4700:31084] @ACTIONCLICKED
> Khants-MacBook-Pro-2:OneChangi khantthulinn$

**Comment by julienXX** [comment]
It's a bug, you can add a `-reply` option in the meantime as a workaround.

**Comment by julienXX** [comment]
Version 2.0.0 as been released with alerter features removed https://github.com/julienXX/terminal-notifier/releases/tag/2.0.0 so this issue should be fixed.
Closing for now, feel free to re-open if it's not the case.
