### ISSUE TITLE
Hidden Answer for Reply? (i.e. to enter secret strings)

### ISSUE THREAD

**Issue by seldamat** [julienXX/terminal-notifier#224]
Is there any support for making the reply to the notification a hidden string?

For example :: https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/PromptforText.html

# Please check everything that applies to your issue:
- [x] I looked in closed issues and it has not already been answered
- [ ] My issue appeared with a terminal-notifier update
- [x] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- the macOS version you use
- terminal-notifier version
- how did you install terminal-notifier (binary download, homebrew, ruby gem...)?
- step-by-step reproduction instructions

**Comment by julienXX** [comment]
Hi @seldamat that would be a cool feature indeed. I'll look into this.

**Comment by seldamat** [comment]
Thanks! Great work on this toolbox - it's very satisfying as a bare bones UI for small programs

**Comment by julienXX** [comment]
Closing for now. Version 2.0.0 as been released with alerter features removed https://github.com/julienXX/terminal-notifier/releases/tag/2.0.0 so this issue is not relevant anymore as the -reply flag is no longer available.
