### ISSUE TITLE
Version checking

### ISSUE THREAD

**Issue by franton** [julienXX/terminal-notifier#226]
The latest (1.8.0) version of Terminal Notifier has moved to a binary from an App bundle. This has rendered all my version checking null and void.

Would it be possible to add a "-version" switch to the next version that outputs a simple "1.8.0" ? I can then use that output to easily detect and update versions as required via the management product my org uses.

**Comment by julienXX** [comment]
@franton yes it's already on the master branch, it will be released with 1.8.1.
