### ISSUE TITLE
File URL fails to open

### ISSUE THREAD

**Issue by vlovich** [julienXX/terminal-notifier#227]
# Please check everything that applies to your issue:
- [X] I looked in closed issues and it has not already been answered
- [X] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- OSX 10.12.5
- terminal-notifier 1.8.0
- homebrew

/opt/homebrew/Cellar/terminal-notifier/1.8.0/bin/terminal-notifier -message test -open "file://$PWD"
> terminal-notifier[35099:7252733] 'file:///Users/vlovich' is not a valid URI.

/opt/homebrew/Cellar/terminal-notifier/1.8.0/bin/terminal-notifier -message test -open "file:/$PWD"
This launches but on click "Show" it just prints @ACTIONCLICKED

I tried a relative path for -open I.e. file://<relative path> & it just prints @ACTIONCLICKED too.

# Common issues and solution:
- I'm using tmux -> see #115
No
- I'm using iterm2 -> see #147
No
- I want to change the icon -> see https://github.com/julienXX/terminal-notifier/issues/197#issuecomment-301305576

Thanks!

**Comment by julienXX** [comment]
Duplicate see #215
