### ISSUE TITLE
Close/Reply buttons always visible

### ISSUE THREAD

**Issue by franton** [julienXX/terminal-notifier#231]
# Please check everything that applies to your issue:
- [x] I looked in closed issues and it has not already been answered
- [x] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
macOS 10.11.x and 10.12.x - the macOS version you use
1.8.0 - terminal-notifier version
binary download - how did you install terminal-notifier (binary download, homebrew, ruby gem...)?
run any basic command "./terminal-notifier -sender "sender.id" -title "Testing" "- step-by-step reproduction instructions

Whenever notifications are sent with version 1.8.0, the close and reply buttons are always visible instead of when they're called with command line switches. This did not occur in versions previous to 1.8.0. Can we go back to previous behaviour?

**Comment by julienXX** [comment]
Hi @franton you can switch the notification style from Alert to Banner in your System Preferences.

**Comment by franton** [comment]
That is not possible to do programmatically via a management system as those settings are stored in a sqlite database somewhere, and it's a bit much to expect a few thousand users to go change this manually.

**Comment by julienXX** [comment]
Sure, the upcoming release will have this setting reverted.
