### ISSUE TITLE
Gatekeeper issues (Killed: 9, CSSMERR_TP_CERT_REVOKED)

### ISSUE THREAD

**Issue by qqilihq** [julienXX/terminal-notifier#233]
## Environment

* macOS 10.12.6
* terminal-notifier 1.8.0
* installation via binary download

## Steps to reproduce

1. Downloaded the new 1.8.0 binary
2. Did some successful tests in Terminal.app
3. Suddenly I cannot launch the binary any longer:
```
$ ./terminal-notifier 
Killed: 9
```
4. Checked via `spctl`:
```
$ spctl --assess terminal-notifier
terminal-notifier: CSSMERR_TP_CERT_REVOKED
```
5. Tried adding an explicit exception via `spctl`:
```
$ spctl --add --label "allow terminal-notifier" ./terminal-notifier
./terminal-notifier: invalid API object reference
```

## Also tried

* re-login, re-boot -- does not help
* `spctl --master-disable` -- does not help
* re-download -- does not help
* `xattr -d com.apple.quarantine terminal-notifier` on the re-downloaded file -- does not help
* old version 1.7.2 -- still works

Known issue or is it just me? Any hints?

**Comment by julienXX** [comment]
Never stumbled across this, I'll try to reproduce.

**Comment by qqilihq** [comment]
Thanks for getting back. Some update: We were able to reproduce this on three different machines in the meantime.

**Comment by julienXX** [comment]
@qqilihq were you able to reproduce using homebrew for installation by any chance?

**Comment by qqilihq** [comment]
@julienXX Woohoo. Just gave it a try: The homebrew version works indeed! (it doesn't seem to be signed, right?)

**Comment by julienXX** [comment]
Right, I'll re-release the binary unsigned then. Thanks for reporting this issue!

**Comment by julienXX** [comment]
Updated the release if you want to try eventually.

**Comment by qqilihq** [comment]
Confirmed working! Many thanks!
