### ISSUE TITLE
Notification Center shows only the latest terminal-notifier message after update to High Sierra

### ISSUE THREAD

**Issue by AbdulHadiParsdorfer** [julienXX/terminal-notifier#242]
Hi,

I used terminal-notifier on macOS Sierra successfully.
I could always find all the notification in the notification centre.

But after updating to High Sierra and updating terminal-notifier from 1.8.0 to 2.0.0 only the latest notification stays in the notification centre all previous notification are gone.

I use terminal-notifier in a simple shell script with Automator:
`terminal-notifier -message 'Upload 600 $filename'`

terminal-notifier is installed via homebrew.

What changed the behaviour in High Sierra or terminal-notifier 2.0.0? 
Do I have to change the script or some settings in High Sierra?
Can't find any answer for this. Thank you so much.

**Comment by julienXX** [comment]
Hi @AbdulHadiParsdorfer do you still encounter this issue?

**Comment by AbdulHadiParsdorfer** [comment]
Yes, you are the first one who is answering. Thank you.

**Comment by AbdulHadiParsdorfer** [comment]
Thank you, I will try it next week. Busy these days ;-)

**Comment by petr-ujezdsky** [comment]
Tried [#222 (comment)](https://github.com/julienXX/terminal-notifier/issues/222#issuecomment-320980802) and nothing changed. Still having the issue.

**Comment by petr-ujezdsky** [comment]
**Update to Mojave solved the issue.**

Versions used:
```
$ terminal-notifier -version
terminal-notifier 2.0.0.

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
```

This floods the notification center with notifications (expected)
```
$ while true; do terminal-notifier -title Test -message "$(date)" -group "$RANDOM"; sleep 1; done
```

This does not flood the notification center, only updates the last notification (expected "group" behavior)
```
$ while true; do terminal-notifier -title Test -message "$(date)" -group "ANYTHING_HERE"; sleep 1; done
* Removing previously sent notification, which was sent on: 2018-10-30 12:24:45 +0000
* Removing previously sent notification, which was sent on: 2018-10-30 12:24:46 +0000
* Removing previously sent notification, which was sent on: 2018-10-30 12:24:47 +0000
```

This issue can be closed IMHO.

**Comment by julienXX** [comment]
On thanks for the report. I’ll close the issue for now.

**Comment by passaca** [comment]
Hi,

unfortunately I have a problem with this:

> This floods the notification center with notifications (expected)
> 
> ```
> $ while true; do terminal-notifier -title Test -message "$(date)" -group "$RANDOM"; sleep 1; done
> ```


It does fill the notification history in the Notification Center with notifications, yes, but on screen (with NC closed), there is always only the most recent notification. It get's immediately replaced by the newer one.

I would like to be able to have several simultaneous notifications on screen. Different group id's definitely do not do the trick for me.

I'm on 2.0.0 and Mac OS 10.14.4

Am I doing anything wrong?

**Comment by petr-ujezdsky** [comment]
Mmm, @passaca same here, the notification is beeing overwritten even though it has different `-group`.
I do not remember if this was happening too, but I think not. I would leave it as bug otherwise..

```
$ terminal-notifier -version
terminal-notifier 2.0.0.
```

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
```
