### ISSUE TITLE
How to prevent notifications from going to into history (like osx notification center)

### ISSUE THREAD

**Issue by mattmcmanus** [julienXX/terminal-notifier#249]
# Please check everything that applies to your issue:
- [x] I looked in closed issues and it has not already been answered
- [ ] My issue appeared with a terminal-notifier update
- [x] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

Howdy! I know, at least for growl and osx, that a user can configure whether the notifications should be kept in the history. I'm wondering if there is a way for the tool to say that it should not keep this in the history preemptively. Is this possible with the current APIs? I didn't see anything in the documentation. The grouping functionality may have the desired result of reducing the noise in the history (if it overwrites what's there) but I'm not sure.

**Comment by julienXX** [comment]
Hi @mattmcmanus yes the `-group` option is what you need, it replaces previous notification with the same groupe identifier.

**Comment by mattmcmanus** [comment]
Awesome. Thanks for letting me know.
