### ISSUE TITLE
Support for emojis as contentImage

### ISSUE THREAD

**Issue by forthrin** [julienXX/terminal-notifier#251]
- I looked in closed issues and it has not already been answered
- the macOS version you use: 10:13
- terminal-notifier version: 2.0.0
- how did you install terminal-notifier: Homebrew

Simply put: `terminal-notifier -contentImage 🍏`. (Alternatively by escape sequences)

**Comment by julienXX** [comment]
The API expects an image file so that won't be possible, sorry.

**Comment by forthrin** [comment]
Following your UNIX philosophy, maybe you (or someone) can come up with a UNIX one-liner that generates a PNG from an emoji, and put that as a tip in the manual file.
