### ISSUE TITLE
Crop contentImage to correct dimensions

### ISSUE THREAD

**Issue by forthrin** [julienXX/terminal-notifier#252]
- I looked in closed issues and it has not already been answered
- the macOS version you use: 10:13
- terminal-notifier version: 2.0.0
- how did you install terminal-notifier: Homebrew

If contentImage has wrong aspect ratio, crop it to create the correct dimensions.

**Comment by julienXX** [comment]
Hi thanks for the idea but I think that's not terminal-notifier responsibility to crop images so sorry but I won't add this feature.

**Comment by forthrin** [comment]
If it's a lot of code and libraries, then I agree. If it's a couple of lines, please reconsider.

**Comment by forthrin** [comment]
I follow that. No problem.
