### ISSUE TITLE
-activate doesn't work if -sender is different

### ISSUE THREAD

**Issue by nhooyr** [julienXX/terminal-notifier#256]
Using an automator app to change the icon. Running this:

```
terminal-notifier -message "Check the terminal" -title Terminal -ignoreDnD -sender com.apple.faketerminal -activate com.apple.Terminal -sound glass
```

Clicking does not make the terminal activate. It does nothing. But if I change the sender to `com.apple.Terminal`, then clicking the notification works fine. Though fine as in #216 

On macOS 10.13.4 and default terminal app.

**Comment by julienXX** [comment]
Thanks for reporting this. Not sure I can do something about it but I'll investigate.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
