### ISSUE TITLE
Why is terminal-notifier is showing in my notification center?

### ISSUE THREAD

**Issue by pentool** [julienXX/terminal-notifier#258]
Not sure if my question is related to this repo, but I just opened my Notification center and I saw a 'terminal-notifier' showing up there. I have no knowledge of ever installing anything like this. I never had it in my notification center. I have searched my entire Mac and there's no app that is called "terminal-notifier". My terminal doesn't recognize this command either. I have searched the net trying to find out what is this and how did this thing got into my system, but I wasn't able to find out anything meaningful. I have node/npm installed, but I had them installed many moons ago (including updates), but I never had this thing in my notification center. Any ideas where is this located on my system and how do I get rid of it?

PS: This is on my desktop Mac. I also have node/npm on my MacBook Pro, but there's no "terminal-notification" on it. Both Macs have identical system (10.11.6).

Thanks

![terminal-notifier](https://user-images.githubusercontent.com/1972916/44827334-7daafe80-abc7-11e8-88ce-0ff84b42f657.jpg)

**Comment by julienXX** [comment]
This must have been installed by a dependency probably node-notifier.

**Comment by pentool** [comment]
But as I was saying, I have searched my Mac and this string doesn't show up in any file. Checked system folders, system and user library, global node modules, etc, nothing. If a dependency installed this there should be some sign somewhere referring to this.

I guess it's time for a clean install of my system...

**Comment by rr0ss0rr** [comment]
See if it's located at: /usr/local/bin/terminal-notifier

You can also issue a "brew list" to see if it's installed (even though there are other package managers that could have been used).

**Comment by julienXX** [comment]
If you run ‘which terminal-notifier’ in a Terminal, does it return anything?

**Comment by pentool** [comment]
@rr0ss0rr Thanks for the reply, but as I mentioned I have already searched all of my Mac's HD and the search result didn't return neither file names nor file contents that would contain the string "terminal-notifier". Also, I do not have brew installed (never used it), so the command doesn't work at the terminal.

@julienXX Nope. Doesn't return anything.

Since I'm not getting any search results for file name hits, neither a file that would contain the string "terminal-notifier", I'm suspecting that somewhere there's an invisible file that is responsible - hence the file is not turning up in the search result. Hope it's not some sort of malware disguised as "terminal-notifier", so I just better do a clean install.

Also, my activity monitor doesn't return any task that would otherwise be running as such. When I check the usage (on this repo), I cannot even issue the command at the terminal "terminal-notifier..." because there's no such command. Weird.

Anyhow. Thank you guys for the feedback. I just go ahead and do a clean install. It usually takes me 30 minutes or so.

**Comment by julienXX** [comment]
to be sure and include hidden directories you can do a « find . -iname terminal-notifier », I’m pretty sure it was installed by a third party development tool. I know node, ruby and elixir have libs that relies on it.

**Comment by pentool** [comment]
@julienXX Thanks, I just tried the search at the terminal as you suggested and I didn't get any results.

I have the same dev setup on both my Mini and MacBook, but interestingly it only shows up on the Mini.

**Comment by JieJiSS** [comment]
Maybe some apps packed `terminal-notifier` inside and it was compiled into binary files (with magic maybe, I don't know)

**Comment by JieJiSS** [comment]
Or it might be renamed by the developer of apps which contain `terminal-notifier`
