### ISSUE TITLE
Spotlight indexing overrides Terminal.app

### ISSUE THREAD

**Issue by franky47** [julienXX/terminal-notifier#264]
# Please check everything that applies to your issue:
- [x] I looked in closed issues and it has not already been answered
- [ ] My issue appeared with a terminal-notifier update
- [x] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- macOS version: 10.14.2
- terminal-notifier version: 1.7.2
- how did you install terminal-notifier: node_module dependency

---

For some reason, when typing "T" to open a Terminal, my Spotlight results prioritizes `terminal-notifier.app` that are installed in all the node_modules (many of my web projects have an indirect dependency on it) over the Terminal.app, which I find extremely frustrating, I used to be able to quickly type cmd + space + T + return and get a Terminal window, but now I get an empty notification instead.

I know it's not related to a source code issue of this project, but does anyone have any idea on how to let Spotlight ignore the `terminal-notifier` apps that live in node_modules ?

**Comment by julienXX** [comment]
Have you tried to reset your Spotlight cache?

**Comment by franky47** [comment]
That seemed to do the trick for now, thanks !

**Comment by romainbessugesmeusy** [comment]
I have the same issue and reseting spotlight did not work as expected. Maybe you could add a never index metadata inside the executable directory ? http://www.filetypehelp.com/purpose-files-metadataneverindex-file-extension/
