### ISSUE TITLE
Errors in Catalina

### ISSUE THREAD

**Issue by selfagency** [julienXX/terminal-notifier#269]
# Please check everything that applies to your issue:
- [X] I looked in closed issues and it has not already been answered
- [ ] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- the macOS version you use `10.15`
- terminal-notifier version `2.0`
- how did you install terminal-notifier (binary download, homebrew, ruby gem...)? `homebrew`
- step-by-step reproduction instructions
  - run `terminal-notifier`

```
2019-07-17 22:37:49.263 terminal-notifier[225:1934184] NSSoftLinking - The function 'SLSIsSuppressedByScreenTime' can't be found in the (null) framework.
```

**Comment by julienXX** [comment]
Thanks for the report, I'm not testing OSX betas so it will have to wait until Catalina is released.

**Comment by selfagency** [comment]
FWIW it's in public beta now so you don't have to have a Developer account in order to test

**Comment by julienXX** [comment]
Thanks but I only have one machine and I don’t want to brick it 😀

**Comment by selfagency** [comment]
I understand entirely, as I've done the same. However, I have discovered with APFS, you can now [install new OS versions in their own containers](https://www.macworld.com/article/3405588/how-to-install-the-macos-catalina-beta-in-its-own-apfs-container.html).

**Comment by selfagency** [comment]
closing this because it's 3 years old, i figure if it ain't fixed yet it ain't gonna be — or if it was, this issue fell by the wayside, and i want to clean up my issues tab
