### ISSUE TITLE
Document yes/no functionality

### ISSUE THREAD

**Issue by dmarcsift** [julienXX/terminal-notifier#270]
Just wondering why I can't seem to find how to add yes/no to my notification like your documentation shows (in graphic example-3). 

# Please check everything that applies to your issue:
- [ x] I looked in closed issues and it has not already been answered
- [ ] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- the macOS version you use - 10.14.6
- terminal-notifier version - 2.0.0
- how did you install terminal-notifier - homebrew
- step-by-step reproduction instructions - N/A

Thanks!

**Comment by julienXX** [comment]
Sorry I need to update this screenshot which is not up to date.
If you want this functionality you have to use alerter as this was removed from terminal-notifier.
