### ISSUE TITLE
How is this different from using `osascript`?

### ISSUE THREAD

**Issue by ZhaofengWu** [julienXX/terminal-notifier#272]
# Please check everything that applies to your issue:
- [x] I looked in closed issues and it has not already been answered

**Comment by jaybarnes** [comment]
It has a bunch of features that osascript doesn't have (as detailed in the README) and is implementable without having to write AppleScript.

**Comment by julienXX** [comment]
You can also use it in various UNIX scripts or have another command pipe into it.
