### ISSUE TITLE
Just use alerter?

### ISSUE THREAD

**Issue by JCsplash** [julienXX/terminal-notifier#278]
@julienXX Thanks for the great library!

It seems like alerter can do everything terminal-notiifer can do, plus having reply / actions. Would you recommend just installing alerter? Or do you recommend having both?

**Comment by JCsplash** [comment]
After digging through the source code, here's what i found. Hope this helps someone. 

1. Terminal-Notifier finishes running immediately after its notifications are sent. Notifications from Alerter **require** user action before it releases from memory. **If you just need notifications without action, use Terminal-Notifier** (don't use alerter and set Notification Style to Banner - otherwise there'll be memory leaks)

2. Terminal-Notifier is packaged as an application and uses applicationDidFinishLaunching(_ aNotification: Notification) to detect whether the user started a new notification or pressed on an existing notification and if so what to do (ex. launch an app, run a shell script..etc). Alerter is packaged as a command line utility and waits for a user response (ex. button press, reply..etc) rather than using applicationDidFinishLaunching in a new instance of Alerter.

_I can see why Terminal-Notifier and Alerter are now separate apps in version 2.0 - but perhaps there is a cleaner way to combine the two. I'll look more into this._

3. Terminal-Notifier has a "Ignore Do Not Disturb" flag which i recently added to alerter in this [pull request](https://github.com/vjeantet/alerter/pull/29).

**Comment by Sergey-Galan** [comment]
https://github.com/vjeantet/alerter/issues/19
