### ISSUE TITLE
terminal-notifier hangs if user is not logged in with graphical shell

### ISSUE THREAD

**Issue by casaschi** [julienXX/terminal-notifier#29]
login on macOs as userOne
open a terminal and run "su - userTwo" to for a shell prompt as userTwo
try terminal-notifier -message Hello

at this point terminal-notifier hangs

I'd rather have the command fail (quickly) and the script to move on rather than the script hanging

**Comment by ddmytrenko** [comment]
The problem still exists. `terminal-notifier` does not work if running using `launchctl load`.
