### ISSUE TITLE
No Notification in macOS12.1

### ISSUE THREAD

**Issue by mattpackwood** [julienXX/terminal-notifier#292]
Hi, I am running:
`$ echo 'Piped Message Data!' | terminal-notifier -sound default`

No errors, and the System asks me to allow Terminal Notifier to send notifactions (which I allow), but after that "nothing happens", no notification, nothing...

Matt

**Comment by HRG1** [comment]
Check that 'Do Not Disturb' in System Preferences/Notifications & Focus is off

**Comment by mattpackwood** [comment]
It is Off.

**Comment by HRG1** [comment]
On my Mac mini (2018) terminal-notifier was installed using homebrew. I have added the commandline tool and terminal-notifier.app to Accessibility. Everything works fine and the notifications are also shown in Notification Center. 

System Preferences/Security & Privacy/Accessibility/terminal-notifier
System Preferences/Security & Privacy/Accessibility/terminal-notifier.app

**Comment by mattpackwood** [comment]
I added `/opt/homebrew/bin/terminal-notifier` to `Accessibility` and it is working!

**Comment by fungiboletus** [comment]
No luck for me, I also added `/opt/homebrew/bin/terminal-notifier` to `Accessibility` and no notifications.

**Comment by limdingwen** [comment]
I am also unable to get any notifications.
