### ISSUE TITLE
Fail to pop up when trigger in python subprogess with crontab -e 

### ISSUE THREAD

**Issue by mobilelifeful** [julienXX/terminal-notifier#298]
# Please check everything that applies to your issue:
- [ X] I looked in closed issues and it has not already been answered
- [ ] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- the macOS version you use  
   macos 11.6.5 (20G527)
- terminal-notifier version 
   terminal-notifier (2.0.0)
- how did you install terminal-notifier (binary download, homebrew, ruby gem...)?
  homebrew
- step-by-step reproduction instructions
cat tt.py
subprocess.run(["terminal-notifier", "-title" "ProjectX", "-subtitle","new","-message", "Finish", "-appIcon", "http://vjeantet.fr/images/logo.png"])

python3 tt.py ok
but with 
crontab -e
*/15 * * * * /usr/local/bin/python3  /Users/x/dev/tt.py

failed

# Common issues and solution:
- I'm using tmux -> see #115
- I'm using iterm2 -> see #147
- I want to change the icon -> see https://github.com/julienXX/terminal-notifier/issues/197#issuecomment-301305576
- I want sticky notifications or action buttons -> please use [alerter](https://github.com/vjeantet/alerter)

Thanks!

**Comment by viranribic** [comment]
I'm facing the exact same issue on "macOS Ventura 13.0", on latest "terminal-notifier 2.0.0". What was the solution that closed this issue?
