### ISSUE TITLE
No notifications during screen recording

### ISSUE THREAD

**Issue by Jack25apr** [julienXX/terminal-notifier#305]
Hello!

I'm experiencing the issue, while recording video (CMD+SHIFT+5) and running in terminal I get no notifications:

STEPS:

1) Star screen video recording via "CMD+SHIFT+5"
2) Trigger terminal notification in terminal via command :
`terminal-notifier -message "foo"`

Result: Nothing new in notification center
Expected result: usual notification popping up at the screen top right corner (Notification Center)

Environment:
- Ventura 13.5 (22G74)
- terminal-notifier 2.0.0.
- installed via homebrew

**Comment by savuori** [comment]
Do you have "allow notifications when mirroring or sharing the display" turned on in the settings?

**Comment by Jack25apr** [comment]
> Do you have "allow notifications when mirroring or sharing the display" turned on in the settings?

Oh, actually no I don't, thanx for hint !
