### ISSUE TITLE
Modify the icon

### ISSUE THREAD

**Issue by pvledoux** [julienXX/terminal-notifier#31]
Hi,

thanks for that very useful tool. Do you think it's possible to change the icon in the notification?

Cheers!

Pv

**Comment by guicheffer** [comment]
@kostajh no way to make it work, unfortunately apple does not let us do it :cry:

**Comment by toshitapandey** [comment]
Is there some way to change the icon for notification, now??

**Comment by guicheffer** [comment]
not sure @toshitapandey, maybe its better using some 3rd party dependency such as gulp/webpack warnings or whatever 😭

**Comment by julienXX** [comment]
@toshitapandey you've got the -appIcon option as stated in the Readme or if you mean the smaller terminal icon see #131
