### ISSUE TITLE
Make notifications 'sticky'

### ISSUE THREAD

**Issue by briancordanyoung** [julienXX/terminal-notifier#33]
I don't know if apples API's allow for it, and I didn't see anyone else ask yet, but it would be great if an option was added to make the notification 'sticky' like the Reminders.app can do. I assume it would be based on the group id, but that group id would stay on screen until the user dismissed it.  Is this possible?

**Comment by y** [comment]
Wouldn't it work if you change globally to Alerts from Banners, then accept an expiration option (and default it if not set), then use a  LaunchAgent to clean up expired notifcations?

**Comment by tjluoma** [comment]
But alerts "steal focus" right? That would be exactly what I do not. I just want something to stay there until I can deal with it.

**Comment by y** [comment]
Alerts don't appear to steal focus. I checked by running this ```sleep 5 && terminal-notifier -message test``` and then switching to a few different apps before the notification was activated. It didn't steal focus from any of them.

**Comment by zeke** [comment]
+1 for per-notification stickiness

**Comment by Lvl2Pillow** [comment]
You can use the `-timeout` flag to dismiss the notification automatically after a duration. This works with the alert style notification. Another idea (which is far from ideal) is to make a copy of the terminal-notifier app and set original to alert style, and the copied one to banner style *shrug*.

**Comment by 360disrupt** [comment]
Timeout doesn't have any effect it stays the same time (~5s) `terminal-notifier -title "Hello" -message "World" -sound morse -timeout 100`

**Comment by glasser** [comment]
Here's a PR to add a note about the system preference to the README: https://github.com/julienXX/terminal-notifier/pull/244
