### ISSUE TITLE
Custom Icon Build

### ISSUE THREAD

**Issue by tybenz** [julienXX/terminal-notifier#43]
Hi. This is more of a XCode question. I cloned your repo and try to build with a custom icon, and got

```
Code Sign error: The identity 'Developer ID Application: Fingertips B.V.' doesn't
match any valid, non-expired certificate/private key pair in your keychains
```

Do I really have to pay the $99 for developer program just to build an app locally?

**Comment by vitorgalvao** [comment]
> If you had previously run the app with the original icon in place, then the system will have cached the icon and I have no idea how to flush that. The simplest way to trigger the new icon to be picked up is by changing the ‘bundle ID’ of the app.

No need. There’s a way simper way:

```bash
touch /path/to/your/app # updates the icon in the finder
kill "$(ps -A | grep '/System/Library/CoreServices/NotificationCenter.app/Contents/MacOS/NotificationCenter' | grep --invert-match 'grep' | awk '{print $1}')" # restarts Notification Center to update the icon there
```
