### ISSUE TITLE
Options notification center

### ISSUE THREAD

**Issue by Alvaroctal** [julienXX/terminal-notifier#62]
Hi, just emailed eloy this morning, in order to ask him if terminal-notifier would have the new Mavericks options in a notification as close, view, delete, etc... 

well, he told me to post in github, so excuse me if it is not the right place for it, i don't really know how to use it correctly.

thanks.

**Comment by danielbayley** [comment]
Why not have something like `-button`/`-action "Name"` which just triggers whatever command is specified by `-execute` when the button is pressed as oppose to the notification itself?

Also, I'm wondering if having callbacks from buttons would bypass the `-sender`/`-execute` mutual exclusivity problem?

**Comment by julienXX** [comment]
@danielbayley that's a good idea, I'll look if it's feasible.

**Comment by decadent** [comment]
FYI, https://github.com/vjeantet/alerter seems to solve this in some manner, and it's forked from terminal-notifier originally.

Of course, it'd still be kinda better if a widely-used-and-available tool had this functionality (and also a switch for sticky alerts).

**Comment by julienXX** [comment]
Interesting. @vjeantet would you be interested in submitting a PR to terminal-notifier instead of maintaining a fork?

**Comment by vjeantet** [comment]
Sans problème :)

i'm not really a gît guru and it's my first app written with objective-C... 
so how to achieve this without breaking anything. ?

**Comment by vjeantet** [comment]
For information, my fork is not packaged as an application bundle, but as a command line only app.

Not sure if it's important...

**Comment by alloy** [comment]
That's awesome. Didn't know Apple had fixed that, I don't think they updated my radar mentioned in the README.

**Comment by julienXX** [comment]
Hey all, @vjeantet work has been merged in 1.7.0 release so I'll close this issue.
