### ISSUE TITLE
Mavericks icon/image support?

### ISSUE THREAD

**Issue by thibaudgg** [julienXX/terminal-notifier#64]
Hi,

It seems like Mavericks notification support custom icon/image per notification, is it possible to add that to `terminal-notifier`? Would be great for guard-rspec success/fail status.

![screen shot 2013-10-28 at 11 08 53](https://f.cloud.github.com/assets/1322/1418594/1d98bdfe-3fb9-11e3-8e68-d5f05e8fbd46.png)

Thanks!

**Comment by onassar** [comment]
@julienXX is there a way to explicitly prevent the contentImage from showing up? When I run it from terminal, the terminal (ITerm actually) icon comes in by default. When I don't define it, or pass in an invalid url, it still pulls in the terminal icon.

**Comment by kennydude** [comment]
@onassar I'm pretty sure you can't due to OSX

**Comment by onassar** [comment]
Gotcha thanks @kennydude

**Comment by WillyWinkel** [comment]
@julienXX using `-appIcon` moves the terminal icon next to the title for me. The appIcon gets replaced by the new image. Is this intended?

**Comment by julienXX** [comment]
@WillyWinkel Yes, that's how Apple designed it regarding the small terminal icon. The only way to have it disappear is to make a custom build with no default icon.

**Comment by WillyWinkel** [comment]
ok cheers! geat project btw, makes me very happy!
