### ISSUE TITLE
Ruby: notification with empty string

### ISSUE THREAD

**Issue by seanchas116** [julienXX/terminal-notifier#84]
It seems that unneeded `''` is displayed when an empty string is passed to `TerminalNotifier.notify`.

``` ruby
TerminalNotifier.notify('')
TerminalNotifier.notify('', title: 'foo', subtitle: 'bar')
```

![image](https://cloud.githubusercontent.com/assets/1025246/2728302/9de70c52-c5ee-11e3-814a-b791f6b592fe.png)

**Comment by julienXX** [comment]
Closing this issue for now as I don't think I'll fix. Don't hesitate to re-open if you really have a need for this behaviour.
