### ISSUE TITLE
Already escaped url escaped again

### ISSUE THREAD

**Issue by hendrikcech** [julienXX/terminal-notifier#95]
terminal-notifier seems to escape already escaped uri components. This is a problem for me since I need to pass an url as part of the path.

The notification that pops up with `-open https://example.com/https%3A%2F%2Fexample.com` opens `https://example.com/https%253A%252F%252Fexample.com`. Using the unescaped url doesn't have the intended effect either: `-open https://example.com/https://example.com` opens `https://example.com/https://example.com`.

I don't really know much about Objective-C but it looks like this could be solved by changing [this](https://github.com/alloy/terminal-notifier/blob/master/Terminal%20Notifier/AppDelegate.m#L193) line of code.

**Comment by FrenchBen** [comment]
Same issue here - Passing: `http://example.com/#abc/xyz.html` should really just open that, without re-encoding it.

**Comment by julienXX** [comment]
Fixed in 1.8.0.
